apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: mabconsulting-co-uk-tls
spec:
  secretName: mabconsulting-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mabconsulting.co.uk
  dnsNames:
    - mabconsulting.co.uk
    - www.mabconsulting.co.uk